// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCvIwTKS8E-dVLbVvWDe0VsPDy0I6RE79c',
    appId: '1:172921488677:web:bb34e1798aaaf9bc3c86cc',
    messagingSenderId: '172921488677',
    projectId: 'innerchildexeapp',
    authDomain: 'innerchildexeapp.firebaseapp.com',
    storageBucket: 'innerchildexeapp.firebasestorage.app',
    measurementId: 'G-K8F6Q27BTY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCuFMO_NqRxJUjblo0ZHNrEsqZVAM0FiGc',
    appId: '1:172921488677:android:3b97a68e4d4aefad3c86cc',
    messagingSenderId: '172921488677',
    projectId: 'innerchildexeapp',
    storageBucket: 'innerchildexeapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDVGxITirYyKaCVLcRHKRmlilica65Qvu0',
    appId: '1:172921488677:ios:99166bf6c3c908aa3c86cc',
    messagingSenderId: '172921488677',
    projectId: 'innerchildexeapp',
    storageBucket: 'innerchildexeapp.firebasestorage.app',
    iosClientId: '172921488677-69do07da350tdmhq2m7jh1g131hekuj9.apps.googleusercontent.com',
    iosBundleId: 'com.example.innerChildApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDVGxITirYyKaCVLcRHKRmlilica65Qvu0',
    appId: '1:172921488677:ios:99166bf6c3c908aa3c86cc',
    messagingSenderId: '172921488677',
    projectId: 'innerchildexeapp',
    storageBucket: 'innerchildexeapp.firebasestorage.app',
    iosClientId: '172921488677-69do07da350tdmhq2m7jh1g131hekuj9.apps.googleusercontent.com',
    iosBundleId: 'com.example.innerChildApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCvIwTKS8E-dVLbVvWDe0VsPDy0I6RE79c',
    appId: '1:172921488677:web:e031bbf02f5b45a13c86cc',
    messagingSenderId: '172921488677',
    projectId: 'innerchildexeapp',
    authDomain: 'innerchildexeapp.firebaseapp.com',
    storageBucket: 'innerchildexeapp.firebasestorage.app',
    measurementId: 'G-Q7G8EN0WYN',
  );

}