// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCCIm1oPDZqhiBanaaOu0ZA6vs57U7QU0U',
    appId: '1:255464204042:web:77b594fa2c70e80efbbcf3',
    messagingSenderId: '255464204042',
    projectId: 'exe-innerchild',
    authDomain: 'exe-innerchild.firebaseapp.com',
    storageBucket: 'exe-innerchild.firebasestorage.app',
    measurementId: 'G-HMW2KHQ2CC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQfTyN7-8gLvcafZ1mN0a0CszorKvoa4o',
    appId: '1:255464204042:android:79c2a7b7f67e1127fbbcf3',
    messagingSenderId: '255464204042',
    projectId: 'exe-innerchild',
    storageBucket: 'exe-innerchild.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAjursC7xDG3lSIwe8tgbWMbq6XmsPwbok',
    appId: '1:255464204042:ios:b81beeb3f31d7217fbbcf3',
    messagingSenderId: '255464204042',
    projectId: 'exe-innerchild',
    storageBucket: 'exe-innerchild.firebasestorage.app',
    iosBundleId: 'com.example.innerChildApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAjursC7xDG3lSIwe8tgbWMbq6XmsPwbok',
    appId: '1:255464204042:ios:b81beeb3f31d7217fbbcf3',
    messagingSenderId: '255464204042',
    projectId: 'exe-innerchild',
    storageBucket: 'exe-innerchild.firebasestorage.app',
    iosBundleId: 'com.example.innerChildApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCCIm1oPDZqhiBanaaOu0ZA6vs57U7QU0U',
    appId: '1:255464204042:web:d875c95ae4f1a65ffbbcf3',
    messagingSenderId: '255464204042',
    projectId: 'exe-innerchild',
    authDomain: 'exe-innerchild.firebaseapp.com',
    storageBucket: 'exe-innerchild.firebasestorage.app',
    measurementId: 'G-4NK0H9XH54',
  );
}
